var nameList = [
  "Time",
  "Past",
  "Future",
  "Dev",
  "Fly",
  "Flying",
  "Soar",
  "Soaring",
  "Power",
  "Falling",
  "Fall",
  "Jump",
  "Cliff",
  "Mountain",
  "Rend",
  "Red",
  "Blue",
  "Green",
  "Yellow",
  "Gold",
  "Demon",
  "Demonic",
  "Panda",
  "Cat",
  "Kitty",
  "Kitten",
  "Zero",
  "Memory",
  "Trooper",
  "XX",
  "Bandit",
  "Fear",
  "Light",
  "Glow",
  "Tread",
  "Deep",
  "Deeper",
  "Deepest",
  "Mine",
  "Your",
  "Worst",
  "Enemy",
  "Hostile",
  "Force",
  "Video",
  "Game",
  "Donkey",
  "Mule",
  "Colt",
  "Cult",
  "Cultist",
  "Magnum",
  "Gun",
  "Assault",
  "Recon",
  "Trap",
  "Trapper",
  "Redeem",
  "Code",
  "Script",
  "Writer",
  "Near",
  "Close",
  "Open",
  "Cube",
  "Circle",
  "Geo",
  "Genome",
  "Germ",
  "Spaz",
  "Shot",
  "Echo",
  "Beta",
  "Alpha",
  "Gamma",
  "Omega",
  "Seal",
  "Squid",
  "Money",
  "Cash",
  "Lord",
  "King",
  "Duke",
  "Rest",
  "Fire",
  "Flame",
  "Morrow",
  "Break",
  "Breaker",
  "Numb",
  "Ice",
  "Cold",
  "Rotten",
  "Sick",
  "Sickly",
  "Janitor",
  "Camel",
  "Rooster",
  "Sand",
  "Desert",
  "Dessert",
  "Hurdle",
  "Racer",
  "Eraser",
  "Erase",
  "Big",
  "Small",
  "Short",
  "Tall",
  "Sith",
  "Bounty",
  "Hunter",
  "Cracked",
  "Broken",
  "Sad",
  "Happy",
  "Joy",
  "Joyful",
  "Crimson",
  "Destiny",
  "Deceit",
  "Lies",
  "Lie",
  "Honest",
  "Destined",
  "Bloxxer",
  "Hawk",
  "Eagle",
  "Hawker",
  "Walker",
  "Zombie",
  "Sarge",
  "Capt",
  "Captain",
  "Punch",
  "One",
  "Two",
  "Uno",
  "Slice",
  "Slash",
  "Melt",
  "Melted",
  "Melting",
  "Fell",
  "Wolf",
  "Hound",
  "Legacy",
  "Sharp",
  "Dead",
  "Mew",
  "Chuckle",
  "Bubba",
  "Bubble",
  "Sandwich",
  "Smasher",
  "Extreme",
  "Multi",
  "Universe",
  "Ultimate",
  "Death",
  "Ready",
  "Monkey",
  "Elevator",
  "Wrench",
  "Grease",
  "Head",
  "Theme",
  "Grand",
  "Cool",
  "Kid",
  "Boy",
  "Girl",
  "Vortex",
  "Paradox",
];

export const generateRandomName = () => {
  return nameList[Math.floor(Math.random() * nameList.length)];
};

let messageList = [
  "Hello everyone! Welcome to the live stream!",
  "Don't forget to like and subscribe if you enjoy the content!",
  "Where is everyone tuning in from? Let me know in the chat!",
  "The topic for today is [Topic]. What are your thoughts?",
  "Shoutout to our newest subscribers: [Subscriber1], [Subscriber2], [Subscriber3]!",
  "I appreciate all the support from our viewers. You guys are amazing!",
  "If you have any questions, feel free to ask in the chat.",
  "I'm curious, what type of content do you want to see more of on the channel?",
  "Big thanks to our sponsors for making this livestream possible!",
  "Let's do a quick poll: What's your favorite part of today's stream so far?",
  "If you're just joining us, we're discussing [Current Topic]. Catch up with the chat!",
  "Special announcement: [Announcement]. Stay tuned for more details!",
  "Thanks for the super chat, [Viewer]! Your support means a lot.",
  "What other topics would you like to see covered in future streams?",
  "A quick reminder to turn on notifications so you never miss a livestream!",
  "Let's take a moment to appreciate the awesome community we've built here.",
  "Fun fact: [Interesting Fact]. Drop your own fun facts in the chat!",
  "I'm thinking of doing a Q&A session soon. Start posting your questions!",
  "The chat is moving so fast, I can't keep up! You guys are incredible!",
];

export const generateRandomMessage = () => {
  return messageList[Math.floor(Math.random() * messageList.length)];
};
